Frequency Encoding
It is a way to utilize the frequency of the categories as labels. In the cases where the frequency is related somewhat to the target variable, it helps the model understand and assign the weight in direct and inverse proportion, depending on the nature of the data. Three-step for this :

* Select a categorical variable you would like to transform.
* Group by the categorical variable and obtain counts of each category.
* Join it back with the training dataset.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'Temperature':['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
       'Color':['Red','Yellow','Blue','Blue',"Red",'Yellow','Red','Yellow','Yellow','Yellow'],
       'Target':[1,1,1,0,1,0,1,0,1,1]}

In [3]:
df = pd.DataFrame(data,columns = ["Temperature","Color","Target"])
df

  Temperature   Color  Target
0         Hot     Red       1
1        Cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1
5        Warm  Yellow       0
6        Warm     Red       1
7         Hot  Yellow       0
8         Hot  Yellow       1
9        Cold  Yellow       1

In [4]:
fe = df.groupby('Temperature').size()/len(df)

In [5]:
df.loc[:,'Temp_freq_encode'] = df['Temperature'].map(fe)

In [6]:
df

  Temperature   Color  Target  Temp_freq_encode
0         Hot     Red       1               0.4
1        Cold  Yellow       1               0.2
2    Very Hot    Blue       1               0.1
3        Warm    Blue       0               0.3
4         Hot     Red       1               0.4
5        Warm  Yellow       0               0.3
6        Warm     Red       1               0.3
7         Hot  Yellow       0               0.4
8         Hot  Yellow       1               0.4
9        Cold  Yellow       1               0.2