In [4]:
import pandas as pd
import numpy as np
import category_encoders as ce

In [5]:
data = {'Temperature':['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
       'Color':['Red','Yellow','Blue','Blue',"Red",'Yellow','Red','Yellow','Yellow','Yellow'],
       'Target':[1,1,1,0,1,0,1,0,1,1]}

In [6]:
df = pd.DataFrame(data,columns = ["Temperature","Color","Target"])
df

  Temperature   Color  Target
0         Hot     Red       1
1        Cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1
5        Warm  Yellow       0
6        Warm     Red       1
7         Hot  Yellow       0
8         Hot  Yellow       1
9        Cold  Yellow       1

In [17]:
encoder = ce.HelmertEncoder(
    cols=["Temperature"],
    drop_invariant=True,
)
dfh = encoder.fit_transform(df['Temperature'])

In [18]:
df = pd.concat([df,dfh],axis = 1)
df

,Temperature,Color,Target,Temperature_0,Temperature_1,Temperature_2,Temperature_0,Temperature_1,Temperature_2,Temperature_0,Temperature_1,Temperature_2,Temperature_0,Temperature_1,Temperature_2
0,Hot,Red,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,Cold,Yellow,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0
2,Very Hot,Blue,1,0.0,2.0,-1.0,0.0,2.0,-1.0,0.0,2.0,-1.0,0.0,2.0,-1.0
3,Warm,Blue,0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0
4,Hot,Red,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
5,Warm,Yellow,0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0
6,Warm,Red,1,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0
7,Hot,Yellow,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
8,Hot,Yellow,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
9,Cold,Yellow,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0