# Ordinal Encoding

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
data = {'Temperature':['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
       'Color':['Red','Yellow','Blue','Blue',"Red",'Yellow','Red','Yellow','Yellow','Yellow'],
       'Target':[1,1,1,0,1,0,1,0,1,1]}

In [3]:
df = pd.DataFrame(data,columns = ["Temperature","Color","Target"])
df

  Temperature   Color  Target
0         Hot     Red       1
1        Cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1
5        Warm  Yellow       0
6        Warm     Red       1
7         Hot  Yellow       0
8         Hot  Yellow       1
9        Cold  Yellow       1

In [4]:
Temp_dict = {'Cold':1,
            'Warm': 2,
            'Hot': 3,
            'Very Hot':4}
df['Temp_Ordinal'] = df.Temperature.map(Temp_dict)
df

  Temperature   Color  Target  Temp_Ordinal
0         Hot     Red       1             3
1        Cold  Yellow       1             1
2    Very Hot    Blue       1             4
3        Warm    Blue       0             2
4         Hot     Red       1             3
5        Warm  Yellow       0             2
6        Warm     Red       1             2
7         Hot  Yellow       0             3
8         Hot  Yellow       1             3
9        Cold  Yellow       1             1